version: "3.4"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=kinesis,dynamodb,cloudwatch
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data # Local directory for saving persistent data
      - DEBUG=1
      - KINESIS_INITIALIZE_STREAMS=therdnotes-delivery-stream:2
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=localstack:4566
    ports:
      - 8001:8001